# Generated by Django 6.0.6 on 2026-07-21 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("import_observations", "0016_api_configuration_migrate_names"),
        ("rules", "0021_rename_approval_remark_rule_rejection_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule_Simulation",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Queued", "Queued"),
                            ("Running", "Running"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Queued",
                        max_length=16,
                    ),
                ),
                ("products", models.JSONField(blank=True, default=list)),
                ("scanner_prefix", models.CharField(blank=True, max_length=255)),
                ("candidate_count", models.BigIntegerField(default=0)),
                ("processed_count", models.BigIntegerField(default=0)),
                ("match_count", models.BigIntegerField(default=0)),
                ("result_observation_ids", models.JSONField(blank=True, default=list)),
                ("rule_definition_hash", models.CharField(max_length=64)),
                ("error_message", models.TextField(blank=True, max_length=2048)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("started", models.DateTimeField(null=True)),
                ("finished", models.DateTimeField(null=True)),
                (
                    "parser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="import_observations.parser",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="rules.rule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rule_simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-created"], name="rules_sim_user_created_idx"),
                    models.Index(fields=["status", "-created"], name="rules_sim_status_created_idx"),
                    models.Index(fields=["rule", "status"], name="rules_sim_rule_status_idx"),
                ],
            },
        ),
    ]
