class Rule_Status:
    RULE_STATUS_APPROVED = "Approved"
    RULE_STATUS_NEEDS_APPROVAL = "Needs approval"
    RULE_STATUS_REJECTED = "Rejected"
    RULE_STATUS_AUTO_APPROVED = "Auto approved"

    RULE_STATUS_CHOICES = [
        (RULE_STATUS_APPROVED, RULE_STATUS_APPROVED),
        (RULE_STATUS_NEEDS_APPROVAL, RULE_STATUS_NEEDS_APPROVAL),
        (RULE_STATUS_REJECTED, RULE_STATUS_REJECTED),
        (RULE_STATUS_AUTO_APPROVED, RULE_STATUS_AUTO_APPROVED),
    ]

    RULE_STATUS_CHOICES_APPROVAL = [
        (RULE_STATUS_APPROVED, RULE_STATUS_APPROVED),
        (RULE_STATUS_REJECTED, RULE_STATUS_REJECTED),
    ]


class Rule_Type:
    RULE_TYPE_FIELDS = "Fields"
    RULE_TYPE_REGO = "Rego"

    RULE_TYPE_CHOICES = [
        (RULE_TYPE_FIELDS, RULE_TYPE_FIELDS),
        (RULE_TYPE_REGO, RULE_TYPE_REGO),
    ]


class Rule_Simulation_Status:
    STATUS_QUEUED = "Queued"
    STATUS_RUNNING = "Running"
    STATUS_COMPLETED = "Completed"
    STATUS_FAILED = "Failed"
    STATUS_CANCELLED = "Cancelled"

    STATUS_CHOICES = [
        (STATUS_QUEUED, STATUS_QUEUED),
        (STATUS_RUNNING, STATUS_RUNNING),
        (STATUS_COMPLETED, STATUS_COMPLETED),
        (STATUS_FAILED, STATUS_FAILED),
        (STATUS_CANCELLED, STATUS_CANCELLED),
    ]

    ACTIVE_STATUSES = [STATUS_QUEUED, STATUS_RUNNING]
    TERMINAL_STATUSES = [STATUS_COMPLETED, STATUS_FAILED, STATUS_CANCELLED]
