# Generated by Django 6.1 on 2026-08-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_product_automatic_vulnerablecode_scanning_enabled_and_more"),
        ("import_observations", "0017_alter_api_configuration_automatic_import_branch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan_Request",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("branch", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.branch")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.product")),
                (
                    "service",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.service"),
                ),
            ],
            options={
                "unique_together": {("product", "branch", "service")},
            },
        ),
    ]
