# Generated by Django 6.1 on 2026-08-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0024_settings_feature_show_product_header_chips"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="feature_osv_scan_after_import",
            field=models.BooleanField(
                default=True, help_text="Scan with OSV after an import has changed the components of a product"
            ),
        ),
    ]
